# Generated by Django 6.0.1 on 2026-01-31 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='顧客名')),
                ('company', models.CharField(blank=True, max_length=100, null=True, verbose_name='会社名')),
                ('address', models.TextField(blank=True, null=True, verbose_name='住所')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '顧客',
                'verbose_name_plural': '顧客',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='項目名')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('unit_price', models.IntegerField(default=0, verbose_name='単価')),
            ],
            options={
                'verbose_name': '請求書明細項目',
                'verbose_name_plural': '請求書明細項目',
            },
        ),
    ]
